# Create a GitHub action to email a report from a file at 6 a.m. daily.
name: Deploy App

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  email-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Email report
        env:
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_TO: